/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TzarDropdown {
        "label"?: string;
        /**
          * @default 'listbox'
         */
        "menuRole": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface TzarHeader {
        /**
          * @default true
         */
        "isLogged": boolean;
    }
    interface TzarIconButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "label": string;
    }
}
export interface TzarDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTzarDropdownElement;
}
declare global {
    interface HTMLTzarDropdownElementEventMap {
        "openChange": boolean;
    }
    interface HTMLTzarDropdownElement extends Components.TzarDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTzarDropdownElementEventMap>(type: K, listener: (this: HTMLTzarDropdownElement, ev: TzarDropdownCustomEvent<HTMLTzarDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTzarDropdownElementEventMap>(type: K, listener: (this: HTMLTzarDropdownElement, ev: TzarDropdownCustomEvent<HTMLTzarDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTzarDropdownElement: {
        prototype: HTMLTzarDropdownElement;
        new (): HTMLTzarDropdownElement;
    };
    interface HTMLTzarHeaderElement extends Components.TzarHeader, HTMLStencilElement {
    }
    var HTMLTzarHeaderElement: {
        prototype: HTMLTzarHeaderElement;
        new (): HTMLTzarHeaderElement;
    };
    interface HTMLTzarIconButtonElement extends Components.TzarIconButton, HTMLStencilElement {
    }
    var HTMLTzarIconButtonElement: {
        prototype: HTMLTzarIconButtonElement;
        new (): HTMLTzarIconButtonElement;
    };
    interface HTMLElementTagNameMap {
        "tzar-dropdown": HTMLTzarDropdownElement;
        "tzar-header": HTMLTzarHeaderElement;
        "tzar-icon-button": HTMLTzarIconButtonElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface TzarDropdown {
        "label"?: string;
        /**
          * @default 'listbox'
         */
        "menuRole"?: string;
        "onOpenChange"?: (event: TzarDropdownCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface TzarHeader {
        /**
          * @default true
         */
        "isLogged"?: boolean;
    }
    interface TzarIconButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label": string;
    }

    interface TzarDropdownAttributes {
        "open": boolean;
        "label": string;
        "menuRole": string;
    }
    interface TzarHeaderAttributes {
        "isLogged": boolean;
    }
    interface TzarIconButtonAttributes {
        "label": string;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "tzar-dropdown": Omit<TzarDropdown, keyof TzarDropdownAttributes> & { [K in keyof TzarDropdown & keyof TzarDropdownAttributes]?: TzarDropdown[K] } & { [K in keyof TzarDropdown & keyof TzarDropdownAttributes as `attr:${K}`]?: TzarDropdownAttributes[K] } & { [K in keyof TzarDropdown & keyof TzarDropdownAttributes as `prop:${K}`]?: TzarDropdown[K] };
        "tzar-header": Omit<TzarHeader, keyof TzarHeaderAttributes> & { [K in keyof TzarHeader & keyof TzarHeaderAttributes]?: TzarHeader[K] } & { [K in keyof TzarHeader & keyof TzarHeaderAttributes as `attr:${K}`]?: TzarHeaderAttributes[K] } & { [K in keyof TzarHeader & keyof TzarHeaderAttributes as `prop:${K}`]?: TzarHeader[K] };
        "tzar-icon-button": Omit<TzarIconButton, keyof TzarIconButtonAttributes> & { [K in keyof TzarIconButton & keyof TzarIconButtonAttributes]?: TzarIconButton[K] } & { [K in keyof TzarIconButton & keyof TzarIconButtonAttributes as `attr:${K}`]?: TzarIconButtonAttributes[K] } & { [K in keyof TzarIconButton & keyof TzarIconButtonAttributes as `prop:${K}`]?: TzarIconButton[K] } & OneOf<"label", TzarIconButton["label"], TzarIconButtonAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tzar-dropdown": LocalJSX.IntrinsicElements["tzar-dropdown"] & JSXBase.HTMLAttributes<HTMLTzarDropdownElement>;
            "tzar-header": LocalJSX.IntrinsicElements["tzar-header"] & JSXBase.HTMLAttributes<HTMLTzarHeaderElement>;
            "tzar-icon-button": LocalJSX.IntrinsicElements["tzar-icon-button"] & JSXBase.HTMLAttributes<HTMLTzarIconButtonElement>;
        }
    }
}
