/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ThemeColorMode } from "./components/button/button";
export { ThemeColorMode } from "./components/button/button";
export namespace Components {
    interface TzrButton {
        /**
          * Text shown inside the button.
         */
        "label": string;
    }
}
export interface TzrButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTzrButtonElement;
}
declare global {
    interface HTMLTzrButtonElementEventMap {
        "themeChange": ThemeColorMode;
    }
    interface HTMLTzrButtonElement extends Components.TzrButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTzrButtonElementEventMap>(type: K, listener: (this: HTMLTzrButtonElement, ev: TzrButtonCustomEvent<HTMLTzrButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTzrButtonElementEventMap>(type: K, listener: (this: HTMLTzrButtonElement, ev: TzrButtonCustomEvent<HTMLTzrButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTzrButtonElement: {
        prototype: HTMLTzrButtonElement;
        new (): HTMLTzrButtonElement;
    };
    interface HTMLElementTagNameMap {
        "tzr-button": HTMLTzrButtonElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface TzrButton {
        /**
          * Text shown inside the button.
         */
        "label": string;
        /**
          * Fired when the button is clicked, with the new theme value.
         */
        "onThemeChange"?: (event: TzrButtonCustomEvent<ThemeColorMode>) => void;
    }

    interface TzrButtonAttributes {
        "label": string;
    }

    interface IntrinsicElements {
        "tzr-button": Omit<TzrButton, keyof TzrButtonAttributes> & { [K in keyof TzrButton & keyof TzrButtonAttributes]?: TzrButton[K] } & { [K in keyof TzrButton & keyof TzrButtonAttributes as `attr:${K}`]?: TzrButtonAttributes[K] } & { [K in keyof TzrButton & keyof TzrButtonAttributes as `prop:${K}`]?: TzrButton[K] } & OneOf<"label", TzrButton["label"], TzrButtonAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tzr-button": LocalJSX.IntrinsicElements["tzr-button"] & JSXBase.HTMLAttributes<HTMLTzrButtonElement>;
        }
    }
}
