name: CI

on:
  pull_request:
    branches: ['release/*']
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build

      - name: Check for a changeset
        if: startsWith(github.base_ref, 'release/')
        run: pnpm changeset status --since=origin/${{ github.base_ref }}

      - name: Lint
        run: pnpm run lint

      - name: Test with coverage
        run: pnpm run test:coverage
