name: Publish

on:
  pull_request:
    types: [closed]
    branches: [master]

concurrency: publish

jobs:
  publish:
    if:
      github.event.pull_request.merged && startsWith(github.head_ref,
      'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Publish @tzardom-ui/react if its version was bumped
        run: node scripts/publish.mjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
