name: Master

on:
  push:
    branches: [master]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: CI
    uses: ./.github/workflows/ci.yml

  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create the GitHub release
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build

      - name: Publish a new version
        run: node scripts/publish.mjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
